spring:
  datasource:
    url: jdbc:mysql://localhost:3306/map-struct
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true




